Po/bd 2659 update dependencies
Bluedot-Innovation/Bluedot-React-Native-Plugin pull request #25
Opened 2021-03-25 05:10 UTC by poborin

2021-03-29 03:14 UTC, duncan-lau commented on ios/Cartfile.resolved
> +github "Bluedot-Innovation/PointSDK-iOS" "15.4.3"
@poborin we just released 15.5.0 :)

2021-04-06 05:27 UTC, duncan-lau commented on ios/Cartfile.resolved
> +github "Bluedot-Innovation/PointSDK-iOS" "15.4.3"
Updated tp 15.5.0

2021-04-06 07:10 UTC, jsprincep requested changes
Please aim at dev/philz-fixes. Nothing is to be merged with master until QA is complete.

2021-04-08 04:10 UTC, duncan-lau commented
> Please aim at dev/philz-fixes. Nothing is to be merged with master until QA is complete.

Done!

2021-04-08 06:05 UTC, jsprincep approved these changes

2021-04-08 06:45 UTC, poborin commented
test comments integration

2021-04-08 06:47 UTC, merged